#!/usr/bin/env node

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

function fail(message) {
  console.error(`DOCX render failed: ${message}`);
  process.exit(2);
}

if (process.argv.length < 4 || process.argv.includes('--help') || process.argv.includes('-h')) {
  console.error('Usage: node render-docx.mjs <report.fodt> <report.docx>');
  process.exit(process.argv.length < 4 ? 1 : 0);
}

const input = path.resolve(process.argv[2]);
const output = path.resolve(process.argv[3]);
if (!fs.existsSync(input)) fail(`input not found: ${input}`);
if (path.extname(input).toLowerCase() !== '.fodt') fail('input must be the .fodt file generated by build-report.mjs');
fs.mkdirSync(path.dirname(output), { recursive: true });

const programFiles = process.env.PROGRAMFILES || 'C:\\Program Files';
const candidates = [
  process.env.REPORT_LIBREOFFICE,
  '/Applications/LibreOffice.app/Contents/MacOS/soffice',
  'soffice',
  'libreoffice',
  path.join(programFiles, 'LibreOffice', 'program', 'soffice.exe')
].filter(Boolean);

const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'report-docx-'));
let lastError = '';
let rendered = false;
try {
  for (let index = 0; index < candidates.length; index += 1) {
    const executable = candidates[index];
    const attempt = path.join(temporary, `attempt-${index}`);
    fs.mkdirSync(attempt, { recursive: true });
    const result = spawnSync(executable, ['--headless', '--convert-to', 'docx', '--outdir', attempt, input], {
      encoding: 'utf8',
      timeout: 120000
    });
    if (result.error?.code === 'ENOENT') continue;
    const generated = path.join(attempt, `${path.parse(input).name}.docx`);
    if (result.status === 0 && fs.existsSync(generated) && fs.statSync(generated).size > 0) {
      fs.copyFileSync(generated, output);
      rendered = true;
      break;
    }
    lastError = result.stderr || result.stdout || result.error?.message || `DOCX conversion exited ${result.status}`;
  }
} finally {
  fs.rmSync(temporary, { recursive: true, force: true });
}

if (rendered) {
  console.log(output);
  process.exit(0);
}
fail(`LibreOffice was not available or could not convert the report. Set REPORT_LIBREOFFICE to its executable path. ${lastError}`.trim());
